@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0  'use +-# for visibility tag
hide empty members

interface Iterator<T> {
    {abstract} hasNext() : boolean
    {abstract} next() : T
    {abstract} remove() : void <<optional>>
}

@enduml